//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCRM.REF.OptimizedPlugins {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CRMAttributesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CRMAttributesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCRM.REF.OptimizedPlugins.CRMAttributesResource", typeof(CRMAttributesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        internal static string AccountEntity {
            get {
                return ResourceManager.GetString("AccountEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accountid.
        /// </summary>
        internal static string AccountIdAttribute {
            get {
                return ResourceManager.GetString("AccountIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ActiveStatusCodeValue {
            get {
                return ResourceManager.GetString("ActiveStatusCodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_attributename.
        /// </summary>
        internal static string AuditConfigAttributeNameAttribute {
            get {
                return ResourceManager.GetString("AuditConfigAttributeNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_entityname.
        /// </summary>
        internal static string AuditConfigEntityNameAttribute {
            get {
                return ResourceManager.GetString("AuditConfigEntityNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_auditconfiguration.
        /// </summary>
        internal static string AuditConfigurationEntity {
            get {
                return ResourceManager.GetString("AuditConfigurationEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_attribute.
        /// </summary>
        internal static string AuditLogAttributeNameAttribute {
            get {
                return ResourceManager.GetString("AuditLogAttributeNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_currentvalue.
        /// </summary>
        internal static string AuditLogCurrentValueAttribute {
            get {
                return ResourceManager.GetString("AuditLogCurrentValueAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_auditlog.
        /// </summary>
        internal static string AuditLogEntityName {
            get {
                return ResourceManager.GetString("AuditLogEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_event.
        /// </summary>
        internal static string AuditLogEventAttribute {
            get {
                return ResourceManager.GetString("AuditLogEventAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_eventtime.
        /// </summary>
        internal static string AuditLogEventTimeAttribute {
            get {
                return ResourceManager.GetString("AuditLogEventTimeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_incidentstatus.
        /// </summary>
        internal static string AuditLogIncidentStatusAttribute {
            get {
                return ResourceManager.GetString("AuditLogIncidentStatusAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_initiatinguserid.
        /// </summary>
        internal static string AuditLogInitiatingUserAttribute {
            get {
                return ResourceManager.GetString("AuditLogInitiatingUserAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_previousvalue.
        /// </summary>
        internal static string AuditLogPreviousValueAttribute {
            get {
                return ResourceManager.GetString("AuditLogPreviousValueAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_servicerequestid.
        /// </summary>
        internal static string AuditLogServiceRequestAttribute {
            get {
                return ResourceManager.GetString("AuditLogServiceRequestAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_buildingid.
        /// </summary>
        internal static string BuildingIdAttribute {
            get {
                return ResourceManager.GetString("BuildingIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string CancelledStatus {
            get {
                return ResourceManager.GetString("CancelledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180620011.
        /// </summary>
        internal static string CompletedStatus {
            get {
                return ResourceManager.GetString("CompletedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_costcentercode.
        /// </summary>
        internal static string CostCenterCode {
            get {
                return ResourceManager.GetString("CostCenterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customerid.
        /// </summary>
        internal static string CustomerIdAttribute {
            get {
                return ResourceManager.GetString("CustomerIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_csr.
        /// </summary>
        internal static string CustomerRepresentative {
            get {
                return ResourceManager.GetString("CustomerRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugOutBoundIntegration.
        /// </summary>
        internal static string DebugOutBoundIntegration {
            get {
                return ResourceManager.GetString("DebugOutBoundIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180620000.
        /// </summary>
        internal static string DeclinedStatus {
            get {
                return ResourceManager.GetString("DeclinedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string DraftStatusCodeValue {
            get {
                return ResourceManager.GetString("DraftStatusCodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailSenderDomainName.
        /// </summary>
        internal static string EmailSenderDomainName {
            get {
                return ResourceManager.GetString("EmailSenderDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_description.
        /// </summary>
        internal static string ExceptionLogDescriptionAttribute {
            get {
                return ResourceManager.GetString("ExceptionLogDescriptionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_exceptionlog.
        /// </summary>
        internal static string ExceptionLogEntity {
            get {
                return ResourceManager.GetString("ExceptionLogEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to incident.
        /// </summary>
        internal static string IncidentEntity {
            get {
                return ResourceManager.GetString("IncidentEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_iocode.
        /// </summary>
        internal static string IoCode {
            get {
                return ResourceManager.GetString("IoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutBoundIntegrationtimeOutInSeconds.
        /// </summary>
        internal static string OutBoundIntegrationtimeOutInSeconds {
            get {
                return ResourceManager.GetString("OutBoundIntegrationtimeOutInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string PendingApporvalStatusValue {
            get {
                return ResourceManager.GetString("PendingApporvalStatusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_primaryproviderid.
        /// </summary>
        internal static string PrimaryProviderIdAttribute {
            get {
                return ResourceManager.GetString("PrimaryProviderIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_problembuilding.
        /// </summary>
        internal static string ProblemBuildingIdAttribute {
            get {
                return ResourceManager.GetString("ProblemBuildingIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_problemclassid.
        /// </summary>
        internal static string ProblemClassIdAttribute {
            get {
                return ResourceManager.GetString("ProblemClassIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_problemroomtype.
        /// </summary>
        internal static string ProblemRoomTypeIdAttribute {
            get {
                return ResourceManager.GetString("ProblemRoomTypeIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_problemtype.
        /// </summary>
        internal static string ProblemTypeAttribute {
            get {
                return ResourceManager.GetString("ProblemTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_problemtypedescription.
        /// </summary>
        internal static string ProblemTypeDescriptionEntityName {
            get {
                return ResourceManager.GetString("ProblemTypeDescriptionEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_problemtypedescriptionid.
        /// </summary>
        internal static string ProblemTypeDescriptionIdAttribute {
            get {
                return ResourceManager.GetString("ProblemTypeDescriptionIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_problemtypedescriptionname.
        /// </summary>
        internal static string ProblemTypeDescriptionNameAttribute {
            get {
                return ResourceManager.GetString("ProblemTypeDescriptionNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_problemtypeid.
        /// </summary>
        internal static string ProblemTypeIdAttribute {
            get {
                return ResourceManager.GetString("ProblemTypeIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_providermatrix.
        /// </summary>
        internal static string ProviderMatrixEntity {
            get {
                return ResourceManager.GetString("ProviderMatrixEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_billablecode.
        /// </summary>
        internal static string ProviderMatrixIOCode {
            get {
                return ResourceManager.GetString("ProviderMatrixIOCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_approvalrequired.
        /// </summary>
        internal static string ProviderMatrixIsApprovalRequired {
            get {
                return ResourceManager.GetString("ProviderMatrixIsApprovalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_providerteam.
        /// </summary>
        internal static string ProviderTeamAttribute {
            get {
                return ResourceManager.GetString("ProviderTeamAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_roomtypeid.
        /// </summary>
        internal static string RoomTypeIdAttribute {
            get {
                return ResourceManager.GetString("RoomTypeIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8/8RoutingPriorities.
        /// </summary>
        internal static string RoutingPriorities8By8 {
            get {
                return ResourceManager.GetString("RoutingPriorities8By8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgement of Receipt of New Email Service Request.
        /// </summary>
        internal static string ServiceRequestAcknowledgementTemplate {
            get {
                return ResourceManager.GetString("ServiceRequestAcknowledgementTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_approver.
        /// </summary>
        internal static string ServiceRequestApprovalManager {
            get {
                return ResourceManager.GetString("ServiceRequestApprovalManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Approval Rejection Email Template.
        /// </summary>
        internal static string ServiceRequestApprovalRejectionTemplate {
            get {
                return ResourceManager.GetString("ServiceRequestApprovalRejectionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Approval Required Template.
        /// </summary>
        internal static string ServiceRequestApprovalRequiredTemplate {
            get {
                return ResourceManager.GetString("ServiceRequestApprovalRequiredTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Approved Email Template.
        /// </summary>
        internal static string ServiceRequestApprovedTemplate {
            get {
                return ResourceManager.GetString("ServiceRequestApprovedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Cancelled Email Template.
        /// </summary>
        internal static string ServiceRequestCancelledTemplate {
            get {
                return ResourceManager.GetString("ServiceRequestCancelledTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_cc.
        /// </summary>
        internal static string ServiceRequestCC {
            get {
                return ResourceManager.GetString("ServiceRequestCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Completed Email Template.
        /// </summary>
        internal static string ServiceRequestCompletedTemplate {
            get {
                return ResourceManager.GetString("ServiceRequestCompletedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Completed Email Template Without Survey.
        /// </summary>
        internal static string ServiceRequestCompletedTemplateWithoutSurvey {
            get {
                return ResourceManager.GetString("ServiceRequestCompletedTemplateWithoutSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_contact.
        /// </summary>
        internal static string ServiceRequestContact {
            get {
                return ResourceManager.GetString("ServiceRequestContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_servicerequestid.
        /// </summary>
        internal static string ServiceRequestIdAttribute {
            get {
                return ResourceManager.GetString("ServiceRequestIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_iocode.
        /// </summary>
        internal static string ServiceRequestIOCode {
            get {
                return ResourceManager.GetString("ServiceRequestIOCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_isapprovalrequired.
        /// </summary>
        internal static string ServiceRequestIsApprovalRequired {
            get {
                return ResourceManager.GetString("ServiceRequestIsApprovalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_servicerequestproblemtypedesc.
        /// </summary>
        internal static string ServiceRequestProblemTypeEntity {
            get {
                return ResourceManager.GetString("ServiceRequestProblemTypeEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_servicerequestproblemtypedescid.
        /// </summary>
        internal static string ServiceRequestProblemTypeIdAttribute {
            get {
                return ResourceManager.GetString("ServiceRequestProblemTypeIdAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customerid.
        /// </summary>
        internal static string ServiceRequestProvider {
            get {
                return ResourceManager.GetString("ServiceRequestProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Reclassified Email Template.
        /// </summary>
        internal static string ServiceRequestReclassifiedTemplate {
            get {
                return ResourceManager.GetString("ServiceRequestReclassifiedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smp_requestorid.
        /// </summary>
        internal static string ServiceRequestRequester {
            get {
                return ResourceManager.GetString("ServiceRequestRequester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Status Change Email Template.
        /// </summary>
        internal static string ServiceRequestStatusChangeTemplate {
            get {
                return ResourceManager.GetString("ServiceRequestStatusChangeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Survey Email Template.
        /// </summary>
        internal static string ServiceRequestSurveyEmailTemplate {
            get {
                return ResourceManager.GetString("ServiceRequestSurveyEmailTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Waiting for Approval Email Template.
        /// </summary>
        internal static string ServiceRequestWaitingForApprovalTemplate {
            get {
                return ResourceManager.GetString("ServiceRequestWaitingForApprovalTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to statuscode.
        /// </summary>
        internal static string StatusCodeAttribute {
            get {
                return ResourceManager.GetString("StatusCodeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to systemuser.
        /// </summary>
        internal static string SystemUserEntity {
            get {
                return ResourceManager.GetString("SystemUserEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to team.
        /// </summary>
        internal static string TeamEntity {
            get {
                return ResourceManager.GetString("TeamEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180620013.
        /// </summary>
        internal static string WaitingForApprovalStatus {
            get {
                return ResourceManager.GetString("WaitingForApprovalStatus", resourceCulture);
            }
        }
    }
}
